### ISSUE TITLE
Update the `latest.json` on the server to contain `filename` and `base_url`

### ISSUE THREAD

**Issue by tombettany** [KanoComputing/kano-burners#34]
Changes on the server need to be made from merging https://github.com/KanoComputing/kano-burners/pull/25.

The `latest.json` should be

```
{
    "name": "Kano OS",
    "version": "Beta 1.3.2",
    "filename": "Kanux-Beta-v1.3.2.img",
    "base_url": "http://downloads.kano.me/public/"
}
```

@pazdera Does this file get automatically generated by the server or is it manually edited?

**Comment by pazdera** [comment]
@tombettany The `latest.json` one is manual - we change it every release based on which image we want to release. I already added those entries: http://downloads.kano.me/public/latest.json

**Comment by tombettany** [comment]
Oh @pazdera, I don't know how I missed that. Perfect. I'll close this then.

**Comment by tombettany** [comment]
@pazdera Looks like we are missing a `public/` on `base_url`. The line should read

 ```
"base_url": "http://downloads.kano.me/public/"
```

not `"base_url": "http://downloads.kano.me/"`

From https://github.com/KanoComputing/kano-burners/issues/27

**Comment by Ealdwulf** [comment]
@tombettany @pazdera Looks like this is fixed now?

**Comment by tombettany** [comment]
Looks like it

**Comment by Ealdwulf** [comment]
@alex5imon I think this can be closed, as it refers to the json file on the server which is correct otherwise the burner would not work at all. Rather than assigning someone to test this ticket, we should make sure that  checking that the burner can fetch the image is on the list of things to do when we make a release.
