### ISSUE TITLE
Setup scripts to build the app with pyinstaller

### ISSUE THREAD

**Issue by radujipa** [KanoComputing/kano-burners#4]
Mac OS and Linux versions should be packaged with `pyinstaller` and `--onefile` option.
For Windows, same process, but potential `tools` need to be provided separately.

For this, a *build script* and a pyinstaller specific `.spec` file should be provided.

 - [x] OSX
 - [ ] Linux
 - [x] Windows

cc @alex5imon @zsero

**Comment by Ealdwulf** [comment]
@alex5imon I think this is old and can be closed. The burner was built with pyinstaller last release.
