### ISSUE TITLE
[Dependency] Check kano-burner version

### ISSUE THREAD

**Issue by radujipa** [KanoComputing/kano-burners#9]
During dependency checking, we should check the version of the burners against a `minimum-version` reported by the server when retrieving `latest.json`.

cc @zsero @alex5imon

**Comment by Ealdwulf** [comment]
@tombettany I have implemented this. A json file containing "min_burner_version" >3 should caus ethe current burner to exit and advise the user to download a new one.

**Comment by Ealdwulf** [comment]
@alex5imon I tested this myself, so I think it can be closed since there is a lot of other stuff to test.
